### ISSUE TITLE
handle web deep links

### ISSUE THREAD

**Issue by onuryurtturk** [jeziellago/Linkt#1]
hi how do we handle the links in the format below

https://somecompany.com/tickets

**Comment by jeziellago** [comment]
Hi @onuryurtturk,
Check the android docs here: https://developer.android.com/training/app-links/deep-linking#adding-filters
The deep link setup in `AndroidManifest.xml` must be done.

**Comment by onuryurtturk** [comment]
ok got it, app links works!
